In [100]:
import pandas as pd
import numpy as np

path = "C:\\Users\\User0\\PycharmProjects\\zoomcamp-hw\\homeworks\\data\\01\\car_fuel_efficiency_2026.csv"

df = pd.read_csv(path)

In [101]:
pd.__version__

'3.0.6'

In [102]:
df.shape

(10000, 11)

In [103]:
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

In [104]:
df.columns.tolist()

['model_year',
 'origin',
 'fuel_type',
 'drivetrain',
 'num_doors',
 'engine_displacement',
 'num_cylinders',
 'horsepower',
 'vehicle_weight',
 'acceleration',
 'fuel_efficiency_mpg']

In [105]:
df["fuel_type"].value_counts()

fuel_type
Gasoline    6913
Diesel      2053
Hybrid      1034
Name: count, dtype: int64

In [106]:
df.isna().sum().sort_values(ascending=False)

horsepower             877
acceleration           264
model_year               0
fuel_type                0
origin                   0
drivetrain               0
num_doors                0
num_cylinders            0
engine_displacement      0
vehicle_weight           0
fuel_efficiency_mpg      0
dtype: int64

In [107]:
df.describe(include="all")

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
count,10000.000000,10000,10000,10000,10000.00000,10000.000000,10000.000000,9123.000000,10000.000000,9736.000000,10000.000000
unique,NaN,3,3,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,USA,Gasoline,Front-wheel drive,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,4202,6913,5519,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,1999.549500,NaN,NaN,NaN,3.50400,2268.807000,6.035200,254.446016,4286.754000,18.888044,29.997700
std,14.207925,NaN,NaN,NaN,0.95209,183.447355,0.542578,22.844613,266.212491,1.279543,2.930245
min,1975.000000,NaN,NaN,NaN,2.00000,1590.000000,4.000000,171.000000,3320.000000,14.000000,19.800000
25%,1987.000000,NaN,NaN,NaN,3.00000,2150.000000,6.000000,239.000000,4110.000000,18.000000,28.000000
50%,2000.000000,NaN,NaN,NaN,4.00000,2270.000000,6.000000,254.000000,4280.000000,18.900000,30.000000
75%,2012.000000,NaN,NaN,NaN,4.00000,2390.000000,6.000000,270.000000,4470.000000,19.700000,31.900000
max,2024.000000,NaN,NaN,NaN,5.00000,3110.000000,8.000000,334.000000,5460.000000,23.800000,41.200000

In [108]:
df["fuel_efficiency_mpg"].sort_values(ascending=False).head(10)

6354    41.2
4077    39.8
2708    39.4
7860    39.2
1800    39.2
2181    39.2
5720    39.1
228     39.1
4430    39.0
6197    39.0
Name: fuel_efficiency_mpg, dtype: float64

In [109]:
hp_not_null = df["horsepower"].dropna()
hp_median = hp_not_null.median()
print(hp_median)

254.0

In [110]:
hp_most_frequent = df["horsepower"].value_counts().idxmax()
print(hp_most_frequent)

252.0

In [111]:
df["horsepower"] = df["horsepower"].fillna(hp_most_frequent)
print(df["horsepower"].isna().sum())

0

In [112]:
hp_new_median = df["horsepower"].median()
print(hp_new_median)

252.0

In [113]:
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

In [114]:
new_df = df[df["origin"] == "Asia"]
new_df.shape

(2994, 11)

In [115]:
new_df_sub = new_df[["vehicle_weight", "model_year"]]
print(new_df_sub)

      vehicle_weight  model_year
2               4240        1996
6               4310        1992
8               4230        1997
10              4420        1978
15              3950        2007
...              ...         ...
9984            4610        2011
9987            4530        2004
9990            3630        1975
9994            4610        1993
9996            4370        1993

[2994 rows x 2 columns]

In [116]:
specific_sub = new_df_sub.head(7)
print(specific_sub)

    vehicle_weight  model_year
2             4240        1996
6             4310        1992
8             4230        1997
10            4420        1978
15            3950        2007
16            4750        2021
22            4450        2019

In [117]:
X = specific_sub.to_numpy()
print(X)

[[4240 1996]
 [4310 1992]
 [4230 1997]
 [4420 1978]
 [3950 2007]
 [4750 2021]
 [4450 2019]]

In [118]:
XTX_inv = np.linalg.inv(X.T @ X)
print(XTX_inv)

[[ 2.96830537e-06 -6.43071025e-06]
 [-6.43071025e-06  1.39675281e-05]]

In [119]:
y = [ 1100, 1300, 800, 900, 1000, 1100, 1200]
w = XTX_inv @ X.T @ y
print(w.sum())

0.36919696904925486